### ISSUE TITLE
KeyError: 'main'  i am getting this error at  'temperature' : r['main']['temp'],

### ISSUE THREAD

**Issue by ansuman13** [PrettyPrinted/weather_app_django#1]
```
Traceback (most recent call last):
  File "/root/p3d2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/p3d2/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/p3d2/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/weather_app_django/the_weather/weather/views.py", line 25, in index
    'temperature' : r['main']['temp'],

```

**Comment by EcoFire** [comment]
I got the same issue (about 18:45 in the Youtube video).

**Comment by jyothiprakash097** [comment]
Bro I have issue with in this course iam trying to add delete button but it not deleted plz help me

**Comment by leslie-alldridge** [comment]
@EcoFire do you still run into this issue?

My code is working fine..

```
 city_weather = {
            'city': city.name,
            'temperature': r['main']['temp'],
            'description': r['weather'][0]['description'],
            'icon': r['weather'][0]['icon'],
        }
```

**Comment by jyothiprakash097** [comment]
Me to fine but I want how to delete the data

**Comment by leslie-alldridge** [comment]
@jyothiprakash097 you can head into the admin panel /admin and delete the data by clicking on the City name and pressing the red delete button. If you want to plumb up a button to do this, i'd recommend: 
1. create a form that posts to a new URL (if you reuse the current route it won't work without new logic)
2. create a function / code up a delete command to the database
3. re-render a new html page or send user back to home page

**Comment by jyothiprakash097** [comment]
Iam tried but iam not getting its shows an error

**Comment by JoshuaSmeda** [comment]
> Iam tried but iam not getting its shows an error

If you could output the error, perhaps we could assist you better? I'm not sure how you expect us to assist without any idea of the error you're getting.

**Comment by leslie-alldridge** [comment]
@jyothiprakash097 I've coded mine up just now to include delete, check my repo it's named django-weather

```
def delete(request, id):

    if request.method == 'POST':
        print(request)
        City.objects.filter(id=id).delete()

    return redirect('/')
```

new path

```
 path('delete/<int:id>', include('weather.urls')),
``` 

To give you a sneak peek. My code is still messy but I'll refine it another time as it's 11pm and I'm ready for bed to be honest..

**Comment by jyothiprakash097** [comment]
Ok I'll try and I'll reply to you

**Comment by leslie-alldridge** [comment]
Awesome, it will work - I've tested over the last 5 mins. Just be sure to include the right routes, function to remove weather, and redirect user back to '/' so it gets the updated weather. I'll be online tomorrow morning so tag me here if there's any problems.

**Comment by jyothiprakash097** [comment]
@leslie-alldridge
I got main error bro what I do now

**Comment by leslie-alldridge** [comment]
What does the error say? Code works fine on my end

**Comment by jyothiprakash097** [comment]
@leslie-alldridge
 keyError at/ 
'main'

**Comment by jyothiprakash097** [comment]
@leslie-alldridge 

Request Method: | POST
-- | --
http://127.0.0.1:8000/delete/2
2.1.7
ValueError
The City could not be created because the data didn't validate.
/media/jyothi/LENOVO/Django/Weather app/venv/lib/python3.6/site-packages/django/forms/models.py in save, line 453
/media/jyothi/LENOVO/Django/Weather app/venv/bin/python
3.6.7
['/media/jyothi/LENOVO/Django/Weather app',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/media/jyothi/LENOVO/Django/Weather app/venv/lib/python3.6/site-packages']
Fri, 8 Mar 2019 10:08:04 +0000

**Comment by leslie-alldridge** [comment]
@jyothiprakash097 I think something is wrong with either your models or migrations. I recommend viewing your database to ensure data is set up correctly and looking over the code / following the video closely to make sure a step isn't missed.

**Comment by jyothiprakash097** [comment]
@leslie-alldridge
Ok thank you bro ,if city is not there then it shows an error,what about you bro

**Comment by leslie-alldridge** [comment]
My entire app works fine with city you will need to check your code sorry.. Must be a typo or error around your db functions or migrations

**Comment by jyothiprakash097** [comment]
Ok tnx bro

**Comment by ajithvallabai** [comment]
@EcoFire  @ansuman13  
1.You need to login to open weather map https://openweathermap.org/ and 
2. then you should get the api keys here https://home.openweathermap.org/api_keys
   and paste it as said in below point .
3. Paste it in views.py 
  `url =url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=<your_api_key>'

**Comment by smahesh29** [comment]
@ansuman13  there are certain changes in the code, in views.py file of weather in place of r = requests.get(url.format(city)).json() write r = requests.get(url.format(city.name)).json()
You can check my repository Weather-App in which I also include delete option.
Link -  https://github.com/smahesh29/Weather-App

**Comment by Moriango** [comment]
I encountered the same issues "KeyError: 'main'" I just deleted the Cities in my database and it seems to have fixed the issue.

**Comment by InesJorge** [comment]
> @EcoFire do you still run into this issue?

You have some item in database that doesn´t exist a city that doesn´t exist so go to your admin site to your database and delete it

**Comment by anandkassu** [comment]
getting an error 'temperature' : r['main']['temp']'
someone please help...............

**Comment by python-personal** [comment]
> getting an error at 'temperature' : r['main']['temp']'
> someone please help...............

Hi, Please delete all the data in the database and recheck, I also faced the same issue

**Comment by styles1-dev** [comment]
> ```
> Traceback (most recent call last):
>   File "/root/p3d2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
>     response = get_response(request)
>   File "/root/p3d2/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/root/p3d2/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/root/weather_app_django/the_weather/weather/views.py", line 25, in index
>     'temperature' : r['main']['temp'],
> ```

 do you solve  'temperature' : r['main']['temp'] this problem i need your help pls

**Comment by styles1-dev** [comment]
i need a help pls  'temperature' : r['main']['temp']
keyerr'main'

**Comment by leslie-alldridge** [comment]
> 
> 
> i need a help pls 'temperature' : r['main']['temp']
> keyerr'main'

make a new issue, please don't attempt to resurrect old ones. Reading the answers above should be all you need...

**Comment by zagal152** [comment]
Thanks a lot python-personal

**Comment by puraabk20** [comment]
temperature = round(json_data["main"]["temp"]-273,1)
KeyError: 'main'

**Comment by Rajeshkanna-k** [comment]
Traceback (most recent call last):
  File "/root/p3d2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/p3d2/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/p3d2/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/weather_app_django/the_weather/weather/views.py", line 25, in index
    'temperature' : r['main']['temp'],
keyerror: 'main'
    this type of error is occur .so how to solve the error .pls help me to sole the error
