### ISSUE TITLE
Not really an issue. But a question 

### ISSUE THREAD

**Issue by TijanAyo** [PrettyPrinted/weather_app_django#9]
Good day, I don’t really have any issue with the web app, but I wanted to ask a question relating to django.... When is it necessary to create models in Django

**Comment by shreyashsrivastava** [comment]
When you need database, you create models. It is used to create tables in the database.

**Comment by TijanAyo** [comment]
> When you need database, you create models. It is used to create tables in the database.

Okay so why don’t we create models for users to store there information in the database or the Django way has that covered 😁

**Comment by shreyashsrivastava** [comment]
You got it, right xD.

**Comment by TijanAyo** [comment]
> You got it, right xD.

Thanks I appreciate
